CREATE DATABASE "BellaWeight";

CREATE TABLE IF NOT EXISTS users
(
	id				SERIAL PRIMARY KEY,
	username		VARCHAR(100)  NOT NULL UNIQUE,
	email	 		VARCHAR(255)  NOT NULL UNIQUE,
	password	 	VARCHAR(255)  NOT NULL,
	created_at		TIMESTAMPTZ   DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS data
(
	id			SERIAL PRIMARY KEY,
	user_id     INTEGER        NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
	name		VARCHAR(255)   NOT NULL,
	height		NUMERIC(5, 2)  NOT NULL,
	weight		NUMERIC(5, 2)  NOT NULL,
	goal_weight	NUMERIC(5, 2)  NOT NULL,
	date		TIMESTAMPTZ	DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS all_weight
(
	id		SERIAL PRIMARY KEY,
	user_id INTEGER       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	weight	NUMERIC(5, 2) NOT NULL,
	date	TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);
